Metrics/LineLength:
  Max: 95
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'Gemfile'
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

# Rails exceptions
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'app/channels/**/*'
    - 'test/**/*'
